volumes:
  pg-data:

services:
  user:
    build: ./authn
    ports:
      - "5000:5000"
    volumes:
      - ./authn:/app
    depends_on:
      - db
  
  db:
    image: postgres:16.4
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_USER: chirper
        - POSTGRES_PASSWORD: chirper