volumes:
  pg-data:


services:
  authn:
    build: ./authn
    ports:
      - "5000:5000"
    volumes:
      - ./authn:/app
    environment:
      DATABASE_URL: postgres://chirper:ch@ngem3$@authn-db:5432/chirper
    depends_on:
      - authn-db

  authn-db:
    image: postgres:17.2
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./authn/scripts/db/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chirper
      POSTGRES_PASSWORD: ch@ngem3$
