definitions:
  login.LoginResponse:
    properties:
      status:
        type: string
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: login
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/login.LoginResponse'
      summary: Login
      tags:
      - login
swagger: "2.0"
