info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: login
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Login
      tags:
      - login
swagger: "2.0"
